import styles from "@/styles/Home.module.css";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <h1> Nest.js Blog </h1>
        <ul className={styles.postList}>
          <li className={styles.post}>
            <h2 className={styles.title}>はじめての投稿</h2>
            <p className={styles.author}>by User</p>
          </li>
          <li className={styles.post}>
            <h2 className={styles.title}>はじめての投稿</h2>
            <p className={styles.author}>by User</p>
          </li>
          <li className={styles.post}>
            <h2 className={styles.title}>はじめての投稿</h2>
            <p className={styles.author}>by User</p>
          </li>
        </ul>
      </div>
    </>
  );
}
